version: '3.8'

secrets:
  db_user_passwd:
    file: ./db_user_passwd
  database_url:
    file: ./database_url
  config_api_secret_key:
    file: ./config_api_secret_key

services:

  # Servicio: Base de datos postgreSQL

  postgres-db:
    image: imarcello51i/postgres:16-alpine
    container_name: config-api-postgres
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_user_passwd
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8" 
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - db_user_passwd
    networks:
      - configapi_net
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Imagen de la splicacion config-api ---------------------------------------------------------------
  config-api:
    image: imarcello51i/config-api:latest
    #container_name: config-api-app
    restart: always
    deploy:
      replicas: 1   # En el video se cambia para asegurar dispomibilidad
      placement:
        constraints:
          - node.role == worker
    ports:
      - "${API_PORT:-8080}:8080"
    environment:
      # Configuración de ASP.NET Core
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_HTTPS_PORT: "8080"
      
      # Variables de PostgreSQL para el entrypoint
      POSTGRES_USER: ${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_USER}
      
      # Cadena de conexión por directorio secret 
      ConnectionStrings__PostgresConnection_FILE: /run/secrets/database_url
      
      # Zona horaria
      TZ: "America/Caracas"
      
      # Control de migraciones
      SKIP_MIGRATIONS: ${SKIP_MIGRATIONS:-false}
      
      # Configuración específica del servicio
      CONFIG_API_DEBUG: 'false'
      CONFIG_API_SECRET_KEY_FILE: /run/secrets/config_api_secret_key
      CONFIG_API_TIME_ZONE: "America/Caracas"
    
    secrets:
      - database_url
      - config_api_secret_key
    networks:
      - configapi_net

# Volúmenes -----------------------------------------------
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfssrv01,rw
      device: ":/data/docker-vols/groupYY/postgres_data"

# Redes
networks:
  configapi_net:
    driver: overlay
    name: config-api-network
